ALTER TABLE tenants ADD COLUMN IF NOT EXISTS business_name VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS primary_color VARCHAR(7) DEFAULT '#6366f1';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS accent_color VARCHAR(7) DEFAULT '#8b5cf6';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS custom_domain VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS welcome_message TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS footer_text VARCHAR(500);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS favicon_url TEXT;