export { useAuth } from './useAuth'
export { useTenant } from './useTenant'
export type { TenantData, TenantStats } from './useTenant'
export { useStudent } from './useStudent'
export type { StudentData, StudentStats } from './useStudent'
